config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :locations
  resources :enemies, only: %i[ create destroy new update ]

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  authenticated do
    root 'pages#index'
  end

end






# bare bones

# module ActionDispatch::Routing
#   class Mapper
#     def authenticated(&block)
#       block.call if env['warden'].authenticated?
#     end

#     def unauthenticated(&block)
#       block.call if env['warden'].unauthenticated?
#     end
#   end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  belongs_to :player
  validates  :monster , presence: true
  validates  :attack , presence: true
  validates  :health , presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many   :players
  validates  :name , presence: true
  validates  :description , presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many   :enemies
  validates  :role, presence: true
  validates  :level, presence: true
  validates  :attack, presence: true
  validates  :health, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :players

  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false}

  validates :email,
    presence: true,
    uniqueness: {case_sensitive: false}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: %i[ index ]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit( :sign_up, keys: %i[ username password email ] )
  end
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  # change
  before_action only: %i[ new edit ] do
    redirect_to new_user_session_path unless current_user&.admin
  end

  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action only: %i[ new edit ] do
    redirect_to new_user_session_path unless current_user&.admin
  end
  def index
    @locations = Location.all
  end
  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RPG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<% @locations&.each do |location| %>
  <div>
    <%= link_to "#{location.name}", location_path(location.id) %>
  </div>
<% end %>

app/views/locations/show.html.erb
<h3><%= @location.name %></h3>
<p><%= @location.description %></p>

app/views/pages/index.html.erb
<% if user_signed_in?  %>
  <p> Welcome, <%= current_user.username %>.</p><br>
  <%= button_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <a href="/users/sign_in">sign-in</a>
  <a href="/users/sign_up">sign-up</a>
<% end %>



<%= link_to  "Locations", locations_path %>